# Generated by Django 5.2.17 on 2026-09-15 07:37

from django.db import migrations


def require_migrated_context(apps, schema_editor):
    User = apps.get_model("users", "User")
    Membership = apps.get_model("organizations", "OrganizationMembership")
    alias = schema_editor.connection.alias
    unresolved = []
    for user in User.objects.using(alias).select_related("site").all().iterator():
        if user.organization_id is None:
            if user.site_id is not None:
                unresolved.append(user.pk)
            continue
        member = Membership.objects.using(alias).filter(user_id=user.pk, organization_id=user.organization_id).first()
        if member is None or user.role not in {"admin", "organization_manager", "inspector", "reviewer", "quality_officer"}:
            unresolved.append(user.pk)
        elif user.site_id and (user.site.organization_id != user.organization_id or member.primary_site_id != user.site_id):
            unresolved.append(user.pk)
    if unresolved:
        raise RuntimeError(
            "Legacy user context is not fully migrated. Reconcile memberships and default sites before cleanup. "
            f"Affected user IDs (first 20): {unresolved[:20]}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firebase_uid'),
        ('organizations', '0003_migrate_legacy_memberships'),
    ]

    operations = [
        migrations.RunPython(require_migrated_context, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='site',
        ),
    ]
