[pytest]
DJANGO_SETTINGS_MODULE = authmed_intern.test_settings
testpaths = tests
pythonpath = .
python_files = tests.py test_*.py *_tests.py
filterwarnings =
    ignore::django.utils.deprecation.RemovedInDjango60Warning

addopts = -p no:cacheprovider
