# Generated by Django 5.2.14 on 2026-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('object_type', models.CharField(blank=True, max_length=128)),
                ('object_id', models.CharField(blank=True, max_length=128)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
