# Generated by Django 5.2.14 on 2026-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdecision',
            name='approved',
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('isolated', 'Isolated'), ('escalated', 'Escalated')], default='accepted', max_length=32),
            preserve_default=False,
        ),
    ]
