# Generated by Django 5.2.11 on 2026-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_remove_reviewdecision_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinspection',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchinspection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='batchinspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=32),
        ),
    ]
