# Generated by Django 5.2.11 on 2026-05-27 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_batchinspection_expiry_date_batchinspection_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('other', 'Other')], default='photo', max_length=32),
        ),
        migrations.AlterField(
            model_name='batchinspection',
            name='outcome',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('isolated', 'Isolated'), ('escalated', 'Escalated')], help_text='Final business decision for the inspection (accepted, isolated, escalated). Set by review/decision workflow.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='batchinspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Inspection workflow status (pending -> in_progress -> completed).\nDo not use for final business outcome; see `outcome`.', max_length=32),
        ),
    ]
