# Generated by Django 5.2.11 on 2026-05-27 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_evidence_created_by_evidence_evidence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskresult',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riskresult',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='riskresult',
            name='flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='riskresult',
            name='suspicion_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16),
        ),
    ]
