# Generated by Django 5.2.14 on 2026-05-29 09:26

import django.db.models.deletion
import inspections.upload_paths
import inspections.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_riskresult_calculated_at_riskresult_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('processor_version', models.CharField(blank=True, max_length=64)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='evidence',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='evidence',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='evidence',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='extraction_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='evidence',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('other', 'Other'), ('package_photo', 'Package photo'), ('shelf_photo', 'Shelf photo'), ('invoice', 'Invoice'), ('barcode', 'Barcode'), ('batch_label', 'Batch label'), ('storage_environment', 'Storage environment'), ('pharmacist_note', 'Pharmacist note')], default='photo', max_length=32),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='image',
            field=models.FileField(upload_to=inspections.upload_paths.inspection_evidence_upload_to, validators=[inspections.validators.validate_inspection_file_extension, inspections.validators.validate_inspection_file_size]),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['inspection', 'evidence_type'], name='inspections_inspect_ec12cd_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['inspection', 'evidence_status'], name='inspections_inspect_d924a3_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['inspection', 'display_order'], name='inspections_inspect_59de7e_idx'),
        ),
        migrations.AddField(
            model_name='ocrtask',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_tasks', to='inspections.evidence'),
        ),
        migrations.AddIndex(
            model_name='ocrtask',
            index=models.Index(fields=['status', 'created_at'], name='inspections_status_39cdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrtask',
            index=models.Index(fields=['evidence', 'status'], name='inspections_evidenc_4b28d6_idx'),
        ),
    ]
