# Generated by Django 5.2.14 on 2026-05-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_ocrtask_alter_evidence_options_evidence_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtask',
            name='execution_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrtask',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrtask',
            name='normalized_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ocrtask',
            name='processing_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ocrtask',
            name='provider_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ocrtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
