# Generated by Django 5.2.14 on 2026-05-29 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_ocrtask_execution_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionProcessingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('current_stage', models.CharField(choices=[('ocr', 'OCR'), ('normalization', 'Normalization'), ('comparison', 'Comparison'), ('scoring', 'Scoring'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='ocr', max_length=32)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('execution_started_at', models.DateTimeField(blank=True, null=True)),
                ('execution_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=64)),
                ('ocr_summary', models.JSONField(blank=True, default=dict)),
                ('comparison_summary', models.JSONField(blank=True, default=dict)),
                ('scoring_summary', models.JSONField(blank=True, default=dict)),
                ('triggered_rules', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=16)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('processing_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='inspections.batchinspection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inspection', 'status'], name='inspections_inspect_989ebd_idx'), models.Index(fields=['inspection', 'created_at'], name='inspections_inspect_6977df_idx'), models.Index(fields=['status', 'current_stage'], name='inspections_status_c67be8_idx')],
            },
        ),
    ]
