# Generated by Django 5.2.17 on 2026-09-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_inspectionprocessingrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionprocessingrun',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionprocessingrun',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionprocessingrun',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
