# Generated by Django 5.2.14 on 2026-05-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_remove_reviewdecision_approved_and_more'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductReference',
        ),
    ]
