# Generated by Django 5.2.14 on 2026-05-28 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0003_productreference_add_fields'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreference',
            options={'ordering': ['organization', 'name']},
        ),
        migrations.AlterField(
            model_name='productreference',
            name='form',
            field=models.CharField(blank=True, help_text='Dosage form (e.g. tablet, capsule, syrup, vial).', max_length=64),
        ),
        migrations.AlterField(
            model_name='productreference',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, this reference is archived/inactive'),
        ),
        migrations.AlterField(
            model_name='productreference',
            name='pack_size',
            field=models.CharField(blank=True, help_text='Pack size or presentation (e.g. 10 tablets)', max_length=64),
        ),
        migrations.AlterField(
            model_name='productreference',
            name='strength',
            field=models.CharField(blank=True, help_text='Strength (e.g. 500 mg, 5 mg/ml)', max_length=64),
        ),
        migrations.AlterField(
            model_name='productreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productreference',
            index=models.Index(fields=['organization', 'sku'], name='products_pr_organiz_23c6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='productreference',
            index=models.Index(fields=['organization', 'name'], name='products_pr_organiz_58b9ee_idx'),
        ),
    ]
