# Generated by Django 5.2.14 on 2026-05-29 09:19

import django.db.models.deletion
import products.upload_paths
import products.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productreference_options_and_more'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreference',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.upload_paths.product_reference_cover_upload_to, validators=[products.validators.validate_reference_image_extension, products.validators.validate_reference_image_file_size]),
        ),
        migrations.AlterField(
            model_name='productreference',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier or manufacturer source for this reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
        migrations.CreateModel(
            name='ProductReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.upload_paths.product_reference_image_upload_to, validators=[products.validators.validate_reference_image_extension, products.validators.validate_reference_image_file_size])),
                ('image_type', models.CharField(choices=[('front_packaging', 'Front packaging'), ('back_packaging', 'Back packaging'), ('blister', 'Blister'), ('label', 'Label'), ('barcode', 'Barcode'), ('leaflet', 'Leaflet'), ('carton', 'Carton'), ('seal', 'Seal')], default='front_packaging', max_length=32)),
                ('angle', models.CharField(blank=True, max_length=64)),
                ('lighting_condition', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, help_text='Source of the reference image (manual, import, partner, etc.).', max_length=128)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='products.productreference')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['product_reference', 'image_type'], name='products_pr_product_a55ce4_idx'), models.Index(fields=['product_reference', 'display_order'], name='products_pr_product_91814d_idx')],
            },
        ),
    ]
