# Generated by Django 5.2.14 on 2026-05-29 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0005_alter_productreference_reference_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('labeling_ready', models.BooleanField(default=False)),
                ('annotation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('needs_review', 'Needs review')], default='pending', max_length=32)),
                ('quality_flag', models.CharField(choices=[('good', 'Good'), ('needs_review', 'Needs review'), ('duplicate', 'Duplicate'), ('blurry', 'Blurry'), ('corrupt', 'Corrupt')], default='needs_review', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DatasetGroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('needs_review', 'Needs review')], default='pending', max_length=32)),
                ('quality_flag', models.CharField(choices=[('good', 'Good'), ('needs_review', 'Needs review'), ('duplicate', 'Duplicate'), ('blurry', 'Blurry'), ('corrupt', 'Corrupt')], default='needs_review', max_length=32)),
                ('annotation_notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.datasetgroup')),
                ('reference_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productreferenceimage')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasetgroup',
            name='reference_images',
            field=models.ManyToManyField(blank=True, related_name='dataset_groups', through='products.DatasetGroupImage', to='products.productreferenceimage'),
        ),
        migrations.AddIndex(
            model_name='datasetgroupimage',
            index=models.Index(fields=['dataset_group', 'annotation_status'], name='products_da_dataset_8ca5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetgroupimage',
            index=models.Index(fields=['dataset_group', 'quality_flag'], name='products_da_dataset_6a641d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetgroupimage',
            unique_together={('dataset_group', 'reference_image')},
        ),
        migrations.AddIndex(
            model_name='datasetgroup',
            index=models.Index(fields=['organization', 'annotation_status'], name='products_da_organiz_18cf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetgroup',
            index=models.Index(fields=['organization', 'quality_flag'], name='products_da_organiz_9d1e80_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetgroup',
            index=models.Index(fields=['organization', 'labeling_ready'], name='products_da_organiz_1a1a0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetgroup',
            unique_together={('organization', 'name')},
        ),
    ]
